### ISSUE TITLE
Default FF styles broken

### ISSUE THREAD

**Issue by tomaskallup** [Etesam913/slick-fox#5]
Hi, first of really great work, from the gif it looks really cool.
However applying this to my Firefox developer edition seems to break its styles. The url bar is offset and has incorrect height, tab icons are offset and overall it looks weird. I'm using default dark theme.
This is how FF looks without your userchrome:
![image](https://user-images.githubusercontent.com/26621166/89030864-a4cd5600-d331-11ea-8f96-21c51b155df0.png)
And this is with yout userchrome:
![image](https://user-images.githubusercontent.com/26621166/89030886-af87eb00-d331-11ea-932c-6e47326077cc.png)

Also it seems to break the url suggestion dropdown (it doesn't show up when using your userchrome).

Is there something I can do to just get the url bar hiding, without the other style changes?

**Comment by Etesam913** [comment]
The urlbar results should be fixed in the most recent commit that I pushed. I presume that the urlbar is not in the correct position because your Firefox is set to compact mode. I attached a gif that shows you how to switch it to the mode that has support in this userchrome.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55665282/89701640-d3859680-d906-11ea-81d0-e91a2cbe068a.gif)
